name: face_recognition
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  # camera: ^0.9.4+21
  flutter:
    sdk: flutter

  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1
  path_provider: ^2.0.10
  awesome_dialog: ^2.2.1
  audioplayers: ^0.20.1
  image_picker: ^0.8.5+3
  google_mlkit_face_detection: ^0.3.0
  permission_handler: ^9.2.0
  animated_splash_screen: ^1.2.0
  camera: ^0.9.7+1



  
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"




flutter:

  
  uses-material-design: true
  
  assets:
  - mobilefacenet.tflite
  - splash-min.jpg
  - alarm.mp3
  - logo.jpg
  - background.jpg
 